[theme]
base = "dark"
primaryColor = "#1DB954"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#1a1a19"
textColor = "#ffffff"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
